Repository nakjun12/Gyul_Box, pull requests merged in 2023-05, with the labels that each got.

#87 [BE] feat - #68 : HouseInfo, Review, ReviewLikes Service 2차 구현
  server/src/main/java/jeju/oneroom/area/controller/AreaController.java
  server/src/main/java/jeju/oneroom/area/repository/AreaRepository.java
  server/src/main/java/jeju/oneroom/area/service/AreaService.java
  server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
  server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
  server/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
  server/src/main/java/jeju/oneroom/houseInfo/repository/HouseInfoRepository.java
  server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
  server/src/main/java/jeju/oneroom/message/entity/Message.java
  server/src/main/java/jeju/oneroom/post/entitiy/Post.java
  server/src/main/java/jeju/oneroom/postComment/entity/PostComment.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
  server/src/main/java/jeju/oneroom/review/entity/Review.java
  server/src/main/java/jeju/oneroom/review/mapper/ReviewMapper.java
  server/src/main/java/jeju/oneroom/review/repository/ReviewRepository.java
  server/src/main/java/jeju/oneroom/review/service/ReviewService.java
  server/src/main/java/jeju/oneroom/reviewLike/controller/ReviewLikeController.java
  server/src/main/java/jeju/oneroom/reviewLike/entity/ReviewLike.java
  server/src/main/java/jeju/oneroom/reviewLike/repository/ReviewLikeRepository.java
  server/src/main/java/jeju/oneroom/reviewLike/service/ReviewLikeService.java
  server/src/main/java/jeju/oneroom/user/controller/UserController.java
  server/src/main/java/jeju/oneroom/user/entity/User.java
  server/src/main/java/jeju/oneroom/user/mapper/UserMapper.java
  server/src/main/java/jeju/oneroom/user/service/UserService.java
  server/src/main/resources/application.yml
  server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
Labels: feat, refactor

#88 [BE] feat - #68 : User Service 2차 구현
  .gitignore
  server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
  server/src/main/java/jeju/oneroom/post/dto/PostDto.java
  server/src/main/java/jeju/oneroom/postComment/dto/PostCommentDto.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
  server/src/main/java/jeju/oneroom/user/controller/UserController.java
  server/src/main/java/jeju/oneroom/user/dto/UserDto.java
  server/src/main/java/jeju/oneroom/user/entity/User.java
  server/src/main/java/jeju/oneroom/user/mapper/UserMapper.java
  server/src/main/java/jeju/oneroom/user/repository/UserRepository.java
  server/src/main/java/jeju/oneroom/user/service/UserService.java
Labels: feat, refactor

#91 [BE] feat - #69 : Area, HouseInfo, Review, ReviewLikes Service 단위 테스트를 위한 비즈니스 로직 점검
  server/src/main/java/jeju/oneroom/area/controller/AreaController.java
  server/src/main/java/jeju/oneroom/common/entity/Rate.java
  server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
  server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
  server/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
  server/src/main/java/jeju/oneroom/houseInfo/mapper/HouseInfoMapper.java
  server/src/main/java/jeju/oneroom/houseInfo/repository/HouseInfoRepository.java
  server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
  server/src/test/java/jeju/oneroom/area/service/AreaServiceTest.java
Labels: feat, refactor

#96 [BE] feat - #69 : HouseInfo, Area Service계층 단위 테스트 일시적 중단
  server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
  server/src/test/java/jeju/oneroom/area/service/AreaServiceTest.java
  server/src/test/java/jeju/oneroom/houseInfo/service/HouseInfoServiceTest.java
Labels: test

#97 [BE] feat - #68 : WebSocket 라이브러리 추가 및 Message 도메인 삭제
  server/build.gradle
  server/src/main/java/jeju/oneroom/message/controller/MessageController.java
  server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
  server/src/main/java/jeju/oneroom/message/entity/Message.java
  server/src/main/java/jeju/oneroom/message/mapper/MessageMapper.java
  server/src/main/java/jeju/oneroom/message/repository/MessageRepository.java
  server/src/main/java/jeju/oneroom/message/service/MessageService.java
  server/src/main/java/jeju/oneroom/user/entity/User.java
  server/src/test/java/jeju/oneroom/message/entity/MessageTest.java
  server/src/test/java/jeju/oneroom/user/entity/UserTest.java
Labels: refactor

#101 [FE] FE api 연결하기
  client/src/component/molecules/bestPosts/BestPost.tsx
  client/src/component/molecules/bestPosts/BestPosts.tsx
  client/src/component/molecules/detailTable/DetailTable.tsx
  client/src/component/molecules/mainCard/MainCard.tsx
  client/src/component/molecules/pagination/PagiNation.tsx
  client/src/component/molecules/reload/Reload.tsx
  client/src/component/molecules/searchBar/SearchBar.module.scss
  client/src/component/molecules/searchBar/SearchBar.tsx
  client/src/component/molecules/stars/Stars.tsx
  client/src/component/organisms/dragCarousel/DragCarousel.tsx
  client/src/component/organisms/editorInformation/Buliding.tsx
  client/src/component/organisms/editorInformation/EditorInformation.module.scss
  client/src/component/organisms/mapfooter/MapFooter.tsx
  client/src/component/organisms/tabs/Tabs.tsx
  client/src/component/templates/header/Header.module.scss
  client/src/component/templates/header/Header.tsx
  client/src/pages/api/search.ts
  client/src/pages/example/index.tsx
  client/src/pages/index.tsx
  client/src/pages/map/index.tsx
  client/src/pages/review/list/[id].tsx
  client/src/styles/globals.scss
  client/src/utils/ConfigHelper.ts
  client/src/utils/Dummy.ts
  client/src/utils/Helper.ts
  client/src/utils/types/types.ts
Labels: feat

#104 [FE] API 연결하기 및 웹소켓 기본 셋팅
  client/package.json
  client/src/component/molecules/categoryStars/CategoryStars.tsx
  client/src/component/molecules/detailTable/DetailTable.tsx
  client/src/component/molecules/pagination/PagiNation.tsx
  client/src/component/molecules/pentagon/Pantagon.tsx
  client/src/component/molecules/review/Review.module.scss
  client/src/component/molecules/review/Review.tsx
  client/src/component/molecules/satisfaction/Satisfaction.tsx
  client/src/component/molecules/stars/DynamicStars.tsx
  client/src/component/organisms/editorInformation/Buliding.tsx
  client/src/component/organisms/editorInformation/GoodBad.tsx
  client/src/component/organisms/editorInformation/Satisfaction.tsx
  client/src/component/organisms/message/message.ts
  client/src/component/organisms/reviews/Reviews.module.scss
  client/src/component/organisms/reviews/Reviews.tsx
  client/src/component/organisms/tabs/Tabs.tsx
  client/src/lib/recoil/currentRoom.ts
  client/src/lib/recoil/profile.ts
  client/src/lib/sample.ts
  client/src/pages/api/editor.ts
  client/src/pages/chat/chat.tsx
  client/src/pages/review/detail/[id].tsx
  client/src/pages/review/editor/index.tsx
  client/src/pages/review/list/[id].tsx
  client/src/utils/ConfigHelper.ts
  client/src/utils/types/types.ts
Labels: feat

#107 [BE] feat - #98 : Oauth2 구현
  server/.gitignore
  server/build.gradle
  server/src/main/java/jeju/oneroom/auth/config/JwtVerificationFilter.java
  server/src/main/java/jeju/oneroom/auth/config/SecurityConfiguration.java
  server/src/main/java/jeju/oneroom/auth/dto/LoginDto.java
  server/src/main/java/jeju/oneroom/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/jeju/oneroom/auth/handler/OAuth2SuccessHandler.java
  server/src/main/java/jeju/oneroom/auth/handler/UserAccessDeniedHandler.java
  server/src/main/java/jeju/oneroom/auth/service/JwtTokenizer.java
  server/src/main/java/jeju/oneroom/auth/token/Token.java
  server/src/main/java/jeju/oneroom/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/jeju/oneroom/auth/utils/ErrorResponder.java
  server/src/main/java/jeju/oneroom/common/entity/Coordinate.java
  server/src/main/java/jeju/oneroom/common/entity/Rate.java
  server/src/main/java/jeju/oneroom/exception/ExceptionCode.java
  server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
  server/src/main/java/jeju/oneroom/response/ErrorResponse.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
  server/src/main/java/jeju/oneroom/review/entity/Review.java
  server/src/main/java/jeju/oneroom/review/repository/ReviewRepository.java
  server/src/main/java/jeju/oneroom/review/service/ReviewService.java
  server/src/main/java/jeju/oneroom/user/entity/User.java
  server/src/main/java/jeju/oneroom/user/repository/UserRepository.java
  server/src/main/java/jeju/oneroom/user/service/UserService.java
  server/src/main/resources/application.yml
  server/src/main/resources/hello-oauth2.html
  server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
Labels: feat, refactor
