Repository nakjun12/Gyul_Box, pull requests merged in 2023-06, with the labels that each got.

#110 [BE] feat - #108 : 외부 open api 데이터 삽입
  server/.gitignore
  server/build.gradle
  server/src/main/java/jeju/oneroom/common/entity/Coordinate.java
  server/src/main/java/jeju/oneroom/common/entity/Rate.java
  server/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
  server/src/main/java/jeju/oneroom/openapi/config/WebClientConfig.java
  server/src/main/java/jeju/oneroom/openapi/controller/OpenApiController.java
  server/src/main/java/jeju/oneroom/openapi/service/GeoPointService.java
  server/src/main/java/jeju/oneroom/openapi/service/OpenApiService.java
  server/src/main/resources/application.properties
  server/src/test/java/jeju/oneroom/area/entity/AreaTest.java
  server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
  server/src/test/java/jeju/oneroom/houseInfo/service/HouseInfoServiceTest.java
  server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
Labels: feat

#112 [BE] feat - #111 : 실시간 채팅 기능 구현
  server/build.gradle
  server/src/main/java/jeju/oneroom/auth/service/JwtTokenizer.java
  server/src/main/java/jeju/oneroom/message/config/RedisConfig.java
  server/src/main/java/jeju/oneroom/message/config/WebSocketConfig.java
  server/src/main/java/jeju/oneroom/message/config/handler/WebSocketHandler.java
  server/src/main/java/jeju/oneroom/message/controller/MessageController.java
  server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
  server/src/main/java/jeju/oneroom/message/entity/Message.java
  server/src/main/java/jeju/oneroom/message/mapper/MessageMapper.java
  server/src/main/java/jeju/oneroom/message/redis/RedisPublisher.java
  server/src/main/java/jeju/oneroom/message/redis/RedisSubscriber.java
  server/src/main/java/jeju/oneroom/message/repository/MessageRepository.java
  server/src/main/java/jeju/oneroom/message/service/MessageService.java
  server/src/main/java/jeju/oneroom/messageroom/controller/MessageRoomController.java
  server/src/main/java/jeju/oneroom/messageroom/dto/MessageRoomDto.java
  server/src/main/java/jeju/oneroom/messageroom/entity/MessageRoom.java
  server/src/main/java/jeju/oneroom/messageroom/entity/MessageRoomStatus.java
  server/src/main/java/jeju/oneroom/messageroom/mapper/MessageRoomMapper.java
  server/src/main/java/jeju/oneroom/messageroom/repository/MessageRoomRepository.java
  server/src/main/java/jeju/oneroom/messageroom/service/MessageRoomService.java
Labels: feat

#114 [BE] feat - #109 : 전반적 코드 리팩토링 및 api 수정
  server/hs_err_pid12136.log
  server/replay_pid12136.log
  server/src/main/java/jeju/oneroom/area/controller/AreaController.java
  server/src/main/java/jeju/oneroom/area/entity/Area.java
  server/src/main/java/jeju/oneroom/area/service/AreaService.java
  server/src/main/java/jeju/oneroom/auth/config/JwtVerificationFilter.java
  server/src/main/java/jeju/oneroom/auth/config/SecurityConfiguration.java
  server/src/main/java/jeju/oneroom/auth/dto/LoginDto.java
  server/src/main/java/jeju/oneroom/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/jeju/oneroom/auth/handler/OAuth2SuccessHandler.java
  server/src/main/java/jeju/oneroom/auth/handler/UserAccessDeniedHandler.java
  server/src/main/java/jeju/oneroom/auth/service/JwtTokenizer.java
  server/src/main/java/jeju/oneroom/auth/token/Token.java
  server/src/main/java/jeju/oneroom/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/jeju/oneroom/auth/utils/ErrorResponder.java
  server/src/main/java/jeju/oneroom/common/dto/ListResponseDto.java
  server/src/main/java/jeju/oneroom/common/dto/MultiResponseDto.java
  server/src/main/java/jeju/oneroom/common/dto/PageInfo.java
  server/src/main/java/jeju/oneroom/common/entity/BaseEntity.java
  server/src/main/java/jeju/oneroom/common/entity/Coordinate.java
  server/src/main/java/jeju/oneroom/common/entity/Rate.java
  server/src/main/java/jeju/oneroom/exception/ExceptionCode.java
  server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
  server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
  server/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
  server/src/main/java/jeju/oneroom/houseInfo/mapper/HouseInfoMapper.java
  server/src/main/java/jeju/oneroom/houseInfo/repository/HouseInfoRepository.java
  server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
  server/src/main/java/jeju/oneroom/openapi/controller/OpenApiController.java
  server/src/main/java/jeju/oneroom/openapi/service/GeoPointService.java
  server/src/main/java/jeju/oneroom/openapi/service/OpenApiService.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
  server/src/main/java/jeju/oneroom/review/entity/Review.java
  server/src/main/java/jeju/oneroom/review/mapper/ReviewMapper.java
  server/src/main/java/jeju/oneroom/review/repository/ReviewRepository.java
  server/src/main/java/jeju/oneroom/review/service/ReviewService.java
  server/src/main/java/jeju/oneroom/reviewLike/controller/ReviewLikeController.java
  server/src/main/java/jeju/oneroom/reviewLike/entity/ReviewLike.java
  server/src/main/java/jeju/oneroom/reviewLike/repository/ReviewLikeRepository.java
  server/src/main/java/jeju/oneroom/reviewLike/service/ReviewLikeService.java
  server/src/main/java/jeju/oneroom/user/controller/UserController.java
  server/src/main/java/jeju/oneroom/user/dto/UserDto.java
  server/src/main/java/jeju/oneroom/user/entity/User.java
  server/src/main/java/jeju/oneroom/user/mapper/UserMapper.java
  server/src/main/java/jeju/oneroom/user/service/UserService.java
  server/src/test/java/jeju/oneroom/area/entity/AreaTest.java
  server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
  server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
Labels: feat, refactor

#115 [BE] feat - #113 : Dto 필드 유효성 검증 추가
  server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
  server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
  server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
  server/src/main/java/jeju/oneroom/user/dto/UserDto.java
  server/src/main/java/jeju/oneroom/user/service/UserService.java
  server/src/main/java/jeju/oneroom/validation/RateValidator.java
  server/src/main/java/jeju/oneroom/validation/ValidRate.java
  server/src/test/java/jeju/oneroom/houseInfo/service/HouseInfoServiceTest.java
Labels: enhancement

#116 [BE] feat - #113 : Global Advice 적용
  server/src/main/java/jeju/oneroom/area/service/AreaService.java
  server/src/main/java/jeju/oneroom/auth/service/JwtTokenizer.java
  server/src/main/java/jeju/oneroom/exception/BusinessLogicException.java
  server/src/main/java/jeju/oneroom/exception/ExceptionCode.java
  server/src/main/java/jeju/oneroom/exception/GlobalExceptionAdvice.java
  server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
  server/src/main/java/jeju/oneroom/messageroom/service/MessageRoomService.java
  server/src/main/java/jeju/oneroom/response/ErrorResponse.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/service/ReviewService.java
  server/src/main/java/jeju/oneroom/reviewLike/service/ReviewLikeService.java
  server/src/main/java/jeju/oneroom/user/service/UserService.java
Labels: feat, refactor

#119 [BE] feat - #118 : Post(게시글) 도메인 기능 추가
  server/.gitignore
  server/src/main/java/jeju/oneroom/common/entity/BaseEntity.java
  server/src/main/java/jeju/oneroom/exception/ExceptionCode.java
  server/src/main/java/jeju/oneroom/post/controller/PostController.java
  server/src/main/java/jeju/oneroom/post/dto/PostDto.java
  server/src/main/java/jeju/oneroom/post/entitiy/Post.java
  server/src/main/java/jeju/oneroom/post/entity/Post.java
  server/src/main/java/jeju/oneroom/post/mapper/PostMapper.java
  server/src/main/java/jeju/oneroom/post/repository/PostRepository.java
  server/src/main/java/jeju/oneroom/post/service/PostService.java
  server/src/main/java/jeju/oneroom/postComment/controller/PostCommentController.java
  server/src/main/java/jeju/oneroom/postComment/dto/PostCommentDto.java
  server/src/main/java/jeju/oneroom/postComment/repository/PostCommentRepository.java
  server/src/main/java/jeju/oneroom/postcomment/controller/PostCommentController.java
  server/src/main/java/jeju/oneroom/postcomment/dto/PostCommentDto.java
  server/src/main/java/jeju/oneroom/postcomment/entity/PostComment.java
  server/src/main/java/jeju/oneroom/postcomment/mapper/PostCommentMapper.java
  server/src/main/java/jeju/oneroom/postcomment/repository/PostCommentRepository.java
  server/src/main/java/jeju/oneroom/postcomment/service/PostCommentService.java
  server/src/main/java/jeju/oneroom/postlike/controller/PostLikeController.java
  server/src/main/java/jeju/oneroom/postlike/entity/PostLike.java
  server/src/main/java/jeju/oneroom/postlike/repository/PostLikeRepository.java
  server/src/main/java/jeju/oneroom/postlike/service/PostLikeService.java
  server/src/main/java/jeju/oneroom/reviewLike/controller/ReviewLikeController.java
  server/src/main/java/jeju/oneroom/user/entity/User.java
  server/src/test/java/jeju/oneroom/area/entity/AreaTest.java
  server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
  server/src/test/java/jeju/oneroom/post/entity/PostTest.java
  server/src/test/java/jeju/oneroom/postcomment/entity/PostCommentTest.java
  server/src/test/java/jeju/oneroom/user/entity/UserTest.java
Labels: fix

#120 [BE] feat - #118 : 코드 리팩토링 및 N+1 성능 최적화
  server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
  server/src/main/java/jeju/oneroom/post/controller/PostController.java
  server/src/main/java/jeju/oneroom/post/dto/PostDto.java
  server/src/main/java/jeju/oneroom/post/entity/Post.java
  server/src/main/java/jeju/oneroom/post/mapper/PostMapper.java
  server/src/main/java/jeju/oneroom/post/repository/PostRepository.java
  server/src/main/java/jeju/oneroom/post/service/PostService.java
  server/src/main/java/jeju/oneroom/postcomment/dto/PostCommentDto.java
  server/src/main/java/jeju/oneroom/postcomment/mapper/PostCommentMapper.java
  server/src/main/java/jeju/oneroom/postcomment/repository/PostCommentRepository.java
  server/src/main/java/jeju/oneroom/review/entity/Review.java
  server/src/test/java/jeju/oneroom/area/entity/AreaTest.java
  server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
  server/src/test/java/jeju/oneroom/post/entity/PostTest.java
  server/src/test/java/jeju/oneroom/postcomment/entity/PostCommentTest.java
  server/src/test/java/jeju/oneroom/user/entity/UserTest.java
Labels: feat

#122 [BE] feat - #118: HouseInfo, Review repository querydsl 적용
  server/src/main/java/jeju/oneroom/common/config/QueryDslConfig.java
  server/src/main/java/jeju/oneroom/houseInfo/repository/HouseInfoCustomRepository.java
  server/src/main/java/jeju/oneroom/houseInfo/repository/HouseInfoCustomRepositoryImpl.java
  server/src/main/java/jeju/oneroom/houseInfo/repository/HouseInfoRepository.java
  server/src/main/java/jeju/oneroom/review/repository/ReviewCustomRepository.java
  server/src/main/java/jeju/oneroom/review/repository/ReviewCustomRepositoryImpl.java
  server/src/main/java/jeju/oneroom/review/repository/ReviewRepository.java
  server/src/main/java/jeju/oneroom/user/entity/User.java
  server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
  server/src/test/java/jeju/oneroom/houseInfo/service/HouseInfoServiceMockTest.java
  server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
Labels: refactor

#123 [BE] feat - #121: Post, PostComment repository querydsl 적용
  server/src/main/java/jeju/oneroom/post/repository/PostCustomRepository.java
  server/src/main/java/jeju/oneroom/post/repository/PostCustomRepositoryImpl.java
  server/src/main/java/jeju/oneroom/post/repository/PostRepository.java
  server/src/main/java/jeju/oneroom/post/service/PostService.java
  server/src/main/java/jeju/oneroom/postcomment/repository/PostCommentCustomRepository.java
  server/src/main/java/jeju/oneroom/postcomment/repository/PostCommentCustomRepositoryImpl.java
  server/src/main/java/jeju/oneroom/postcomment/repository/PostCommentRepository.java
  server/src/main/java/jeju/oneroom/postcomment/service/PostCommentService.java
Labels: refactor

#125 [BE] feat - #124: Post, PostComment, Review 도메인 동일 유저 로직 추가
  server/src/main/java/jeju/oneroom/exception/ExceptionCode.java
  server/src/main/java/jeju/oneroom/exception/GlobalExceptionAdvice.java
  server/src/main/java/jeju/oneroom/post/controller/PostController.java
  server/src/main/java/jeju/oneroom/post/dto/PostDto.java
  server/src/main/java/jeju/oneroom/post/entity/Post.java
  server/src/main/java/jeju/oneroom/post/service/PostService.java
  server/src/main/java/jeju/oneroom/postcomment/controller/PostCommentController.java
  server/src/main/java/jeju/oneroom/postcomment/dto/PostCommentDto.java
  server/src/main/java/jeju/oneroom/postcomment/entity/PostComment.java
  server/src/main/java/jeju/oneroom/postcomment/service/PostCommentService.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
  server/src/main/java/jeju/oneroom/review/entity/Review.java
  server/src/main/java/jeju/oneroom/review/service/ReviewService.java
Labels: feat
