Repository nakjun12/Gyul_Box, pull requests merged in 2023-04, with the labels that each got.

#6 feat - #2 : Si, Town, Houseinfo, Review, Coordinate 엔티티 생성
  oneroom/src/main/java/jeju/oneroom/coordinate/entity/Coordinate.java
  oneroom/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
  oneroom/src/main/java/jeju/oneroom/review/entity/Review.java
  oneroom/src/main/java/jeju/oneroom/si/entity/Si.java
  oneroom/src/main/java/jeju/oneroom/town/entity/Town.java
Labels: feat

#7 feat - #2 : user, post, postComment, message 엔티티 생성
  oneroom/build.gradle
  oneroom/src/main/java/jeju/oneroom/Post/entitiy/Post.java
  oneroom/src/main/java/jeju/oneroom/message/entity/Message.java
  oneroom/src/main/java/jeju/oneroom/postComment/entity/PostComment.java
  oneroom/src/main/java/jeju/oneroom/user/controller/UserController.java
  oneroom/src/main/java/jeju/oneroom/user/entity/User.java
  oneroom/src/main/resources/application.yml
Labels: feat

#16 feat - #9 : Si, Town, Houseinfo, Review Controller 생성
  oneroom/src/main/java/jeju/oneroom/common/entity/Coordinate.java
  oneroom/src/main/java/jeju/oneroom/common/entity/Rate.java
  oneroom/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
  oneroom/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
  oneroom/src/main/java/jeju/oneroom/message/entity/Message.java
  oneroom/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  oneroom/src/main/java/jeju/oneroom/review/entity/Review.java
  oneroom/src/main/java/jeju/oneroom/si/controller/SiController.java
  oneroom/src/main/java/jeju/oneroom/si/entity/Si.java
  oneroom/src/main/java/jeju/oneroom/town/controller/TownController.java
  oneroom/src/main/java/jeju/oneroom/town/entity/Town.java
  oneroom/src/main/java/jeju/oneroom/user/entity/User.java
Labels: feat

#21 [FE] -> [Client] 프론트엔드 초기 설정 완
  client/.gitignore
  client/package.json
  client/src/component/atoms/Button/Button.tsx
  client/src/component/icon/gyul_main.png
  client/src/component/molecules/Card/Card.tsx
  client/src/component/molecules/Form/from.tsx
  client/src/component/organisms/Footer/footer.tsx
  client/src/component/organisms/Header/header.tsx
  client/src/component/templates/Home/home.tsx
  client/src/lib/Helper.tsx
  client/src/lib/recoil/ex.ts
  client/src/lib/recoil/ex_file.tsx
  client/src/lib/swr/ex.tsx
  client/src/pages/_app.tsx
  client/src/types/typelist.ts
Labels: feat

#22 [BE] feat - #10 : Si, Town, Houseinfo, Review Dto 생성
  server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
  server/src/main/java/jeju/oneroom/review/entity/Review.java
  server/src/main/java/jeju/oneroom/si/dto/SiDto.java
  server/src/main/java/jeju/oneroom/town/dto/TownDto.java
Labels: feat

#23 [BE] feat - #10 : post, postComment, message, user controller DTO 1차 생성
  server/src/main/java/jeju/oneroom/Post/controller/PostController.java
  server/src/main/java/jeju/oneroom/Post/dto/PostDto.java
  server/src/main/java/jeju/oneroom/Post/entitiy/Post.java
  server/src/main/java/jeju/oneroom/message/controller/MessageController.java
  server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
  server/src/main/java/jeju/oneroom/postComment/controller/PostCommentController.java
  server/src/main/java/jeju/oneroom/postComment/dto/PostCommentDto.java
  server/src/main/java/jeju/oneroom/postComment/entity/PostComment.java
  server/src/main/java/jeju/oneroom/user/controller/UserController.java
  server/src/main/java/jeju/oneroom/user/dto/UserDto.java
  server/src/main/java/jeju/oneroom/user/entity/User.java
Labels: feat

#28 [FE] -> [Client] 헤더 초기 설정
  client/src/component/atoms/Category/Category.tsx
  client/src/component/atoms/GrayStar/GrayStart.tsx
  client/src/component/atoms/Interest/Interest.tsx
  client/src/component/atoms/Map/Map.tsx
  client/src/component/atoms/OrangeButton/OrangeButton.tsx
  client/src/component/atoms/ReviewBox/ReviewBox.tsx
  client/src/component/atoms/TextInput/TextInput.tsx
  client/src/component/atoms/WhiteButton/WhiteButton.tsx
  client/src/component/atoms/YellowStar/YellowStart.tsx
  client/src/component/molecules/Form/from.tsx
  client/src/component/organisms/Footer/footer.tsx
  client/src/component/organisms/Header/Header.module.scss
  client/src/component/organisms/Header/header.tsx
  client/src/pages/index.tsx
  client/src/styles/_variables.scss
  client/src/styles/globals.scss
Labels: feat

#34 [BE] feat - #30 : post, postComment, message, user 엔티티에 baseEntity ex…
  server/src/main/java/jeju/oneroom/Post/entitiy/Post.java
  server/src/main/java/jeju/oneroom/message/entity/Message.java
  server/src/main/java/jeju/oneroom/postComment/entity/PostComment.java
  server/src/main/java/jeju/oneroom/user/entity/User.java
Labels: feat, fix

#37 [FE] -> [Client] 헤더 작업 완료
  client/public/icon/gyulLogo.png
  client/src/component/atoms/lnterest/Interest.tsx
  client/src/component/organisms/Header/Header.module.scss
  client/src/component/organisms/Header/header.tsx
  client/src/styles/_variables.scss
  client/src/styles/globals.scss
Labels: feat

#45 [FE] -> [Client] 메인페이지 lottie, searchbar 완 , board 작업 중
  client/public/icon/gyulLogo.png
  client/public/icon/mainGyul.jpg
  client/src/component/atoms/Lottie/MainLottie.module.scss
  client/src/component/atoms/Lottie/MainLottie.tsx
  client/src/component/molecules/searchBar/SearchBar.module.scss
  client/src/component/molecules/searchBar/SearchBar.tsx
  client/src/component/organisms/Footer/footer.tsx
  client/src/component/organisms/Header/Header.module.scss
  client/src/component/organisms/Header/header.tsx
  client/src/pages/_app.tsx
  client/src/pages/home.module.scss
  client/src/pages/index.tsx
Labels: feat

#46 [BE] feat - #35 : Si, Town, Houseinfo, Review mapper 생
  server/build.gradle
  server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
  server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
  server/src/main/java/jeju/oneroom/houseInfo/mapper/HouseInfoMapper.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
  server/src/main/java/jeju/oneroom/review/mapper/ReviewMapper.java
  server/src/main/java/jeju/oneroom/si/controller/SiController.java
  server/src/main/java/jeju/oneroom/si/dto/SiDto.java
  server/src/main/java/jeju/oneroom/si/entity/Si.java
  server/src/main/java/jeju/oneroom/si/mapper/SiMapper.java
  server/src/main/java/jeju/oneroom/town/controller/TownController.java
  server/src/main/java/jeju/oneroom/town/dto/TownDto.java
  server/src/main/java/jeju/oneroom/town/mapper/TownMapper.java
  server/src/main/resources/application.yml
  server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
Labels: feat

#47 [BE] feat - #35 : post, postComment, message, user mapper 구현
  server/build.gradle
  server/src/main/java/jeju/oneroom/Post/controller/PostController.java
  server/src/main/java/jeju/oneroom/Post/dto/PostDto.java
  server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
  server/src/main/java/jeju/oneroom/postComment/controller/PostCommentController.java
  server/src/main/java/jeju/oneroom/postComment/dto/PostCommentDto.java
  server/src/main/java/jeju/oneroom/user/controller/UserController.java
  server/src/main/java/jeju/oneroom/user/dto/UserDto.java
  server/src/main/resources/application.yml
  server/src/test/java/jeju/oneroom/Post/entitiy/PostTest.java
  server/src/test/java/jeju/oneroom/postComment/entity/PostCommentTest.java
  server/src/test/java/jeju/oneroom/user/entity/UserTest.java
Labels: feat

#48 [BE] feat - #35 : post, postComment, message, user controller Mapstru…
  server/src/main/java/jeju/oneroom/Post/mapper/PostMapper.java
  server/src/main/java/jeju/oneroom/message/mapper/MessageMapper.java
  server/src/main/java/jeju/oneroom/postComment/mapper/PostCommentMapper.java
  server/src/main/java/jeju/oneroom/user/dto/UserDto.java
  server/src/main/java/jeju/oneroom/user/mapper/UserMapper.java
Labels: feat

#49 [BE] feat - #35 : Si, Town, Houseinfo, Review mapper 수정 및 commen 생성
  server/src/main/java/jeju/oneroom/common/dto/ListResponseDto.java
  server/src/main/java/jeju/oneroom/common/dto/MultiResponseDto.java
  server/src/main/java/jeju/oneroom/common/dto/PageInfo.java
  server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
  server/src/main/java/jeju/oneroom/houseInfo/mapper/HouseInfoMapper.java
  server/src/main/java/jeju/oneroom/houseInfo/repository/HouseInfoRepository.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/mapper/ReviewMapper.java
  server/src/main/java/jeju/oneroom/review/repository/ReviewRepository.java
  server/src/main/java/jeju/oneroom/si/controller/SiController.java
  server/src/main/java/jeju/oneroom/si/mapper/SiMapper.java
  server/src/main/java/jeju/oneroom/town/controller/TownController.java
  server/src/main/java/jeju/oneroom/town/mapper/TownMapper.java
  server/src/main/java/jeju/oneroom/town/repository/TownRepository.java
  server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
  server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
  server/src/test/java/jeju/oneroom/town/entity/TownTest.java
Labels: feat

#51 [BE] feat - #35 : post, postComment, message, User mapstruct 수정 및 get…
  server/src/main/java/jeju/oneroom/Post/controller/PostController.java
  server/src/main/java/jeju/oneroom/Post/mapper/PostMapper.java
  server/src/main/java/jeju/oneroom/Post/repository/PostRepository.java
  server/src/main/java/jeju/oneroom/postComment/controller/PostCommentController.java
  server/src/main/java/jeju/oneroom/user/dto/UserDto.java
  server/src/test/java/jeju/oneroom/Post/entitiy/PostTest.java
  server/src/test/java/jeju/oneroom/message/entity/MessageTest.java
  server/src/test/java/jeju/oneroom/postComment/entity/PostCommentTest.java
  server/src/test/java/jeju/oneroom/user/entity/UserTest.java
Labels: feat

#53 [FE -> Client] 메인페이지 게시글 작성 완
  client/src/pages/index.tsx
Labels: feat

#54 [FE] -> [Client] bug fixx
  client/public/icon/gyulLogo.png
  client/src/component/mainBoard/MainBoard.tsx
  client/src/component/mainBoard/MianBpard.module.scss
  client/src/component/mainBoard/boardContents/BoardContents.module.scss
  client/src/component/mainBoard/boardContents/BoardContents.tsx
  client/src/pages/home.module.scss
  client/src/pages/index.tsx
Labels: bug

#55 44 fe mypage markup
  client/package.json
  client/src/component/atoms/Category/Category.tsx
  client/src/component/molecules/tabPanel/MypagePanel.tsx
  client/src/component/molecules/tabPanel/tabPanel.module.scss
  client/src/component/organisms/tabs/Tabs.module.scss
  client/src/component/organisms/tabs/Tabs.tsx
  client/src/component/templates/modal/InterestModal.tsx
  client/src/component/templates/modal/Modal.module.scss
  client/src/lib/Dummy.tsx
  client/src/pages/mypage/index.tsx
Labels: feat

#58 [BE] feat - #35 : post, postComment, message, user getMapping에 따른 DTO…
  server/src/main/java/jeju/oneroom/Post/controller/PostController.java
  server/src/main/java/jeju/oneroom/Post/dto/PostDto.java
  server/src/main/java/jeju/oneroom/Post/mapper/PostMapper.java
  server/src/main/java/jeju/oneroom/Post/repository/PostRepository.java
  server/src/main/java/jeju/oneroom/message/controller/MessageController.java
  server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
  server/src/main/java/jeju/oneroom/message/mapper/MessageMapper.java
  server/src/main/java/jeju/oneroom/message/repository/MessageRepository.java
  server/src/main/java/jeju/oneroom/user/dto/UserDto.java
  server/src/main/java/jeju/oneroom/user/mapper/UserMapper.java
  server/src/test/java/jeju/oneroom/message/entity/MessageTest.java
  server/src/test/java/jeju/oneroom/user/entity/UserTest.java
Labels: feat

#59 [BE] feat - #11 : post, postComment, message, user api 문서화를 위한 구현
  server/src/main/java/jeju/oneroom/Post/controller/PostController.java
  server/src/main/java/jeju/oneroom/Post/mapper/PostMapper.java
  server/src/main/java/jeju/oneroom/Post/repository/PostRepository.java
  server/src/main/java/jeju/oneroom/message/controller/MessageController.java
  server/src/main/java/jeju/oneroom/message/dto/MessageDto.java
  server/src/main/java/jeju/oneroom/message/mapper/MessageMapper.java
  server/src/main/java/jeju/oneroom/message/repository/MessageRepository.java
  server/src/main/java/jeju/oneroom/postComment/entity/PostComment.java
  server/src/main/java/jeju/oneroom/postComment/mapper/PostCommentMapper.java
  server/src/test/java/jeju/oneroom/message/entity/MessageTest.java
  server/src/test/java/jeju/oneroom/postComment/entity/PostCommentTest.java
Labels: feat

#65 [BE] feat - #11 : Api 명세서 작성을 위한 리팩토링
  .gitignore
  server/hs_err_pid9704.log
  server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
  server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
  server/src/main/java/jeju/oneroom/houseInfo/mapper/HouseInfoMapper.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
  server/src/main/java/jeju/oneroom/review/mapper/ReviewMapper.java
  server/src/main/java/jeju/oneroom/review/repository/ReviewRepository.java
  server/src/main/java/jeju/oneroom/si/dto/SiDto.java
  server/src/main/java/jeju/oneroom/si/entity/Si.java
  server/src/main/java/jeju/oneroom/si/mapper/SiMapper.java
  server/src/main/java/jeju/oneroom/town/controller/TownController.java
  server/src/main/java/jeju/oneroom/town/dto/TownDto.java
  server/src/main/java/jeju/oneroom/town/mapper/TownMapper.java
  server/src/test/java/jeju/oneroom/OneroomApplicationTests.java
  server/src/test/java/jeju/oneroom/Post/entitiy/PostTest.java
  server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
  server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
  server/src/test/java/jeju/oneroom/si/entity/SiEntityTest.java
  server/src/test/java/jeju/oneroom/town/entity/TownTest.java
  server/src/test/java/jeju/oneroom/user/entity/UserTest.java
Labels: refactor

#75 [BE] refactor - #11 : Town -> Area로 변경 및 Si 삭제로 인한 리팩토링
  server/hs_err_pid4284.log
  server/src/main/java/jeju/oneroom/area/controller/AreaController.java
  server/src/main/java/jeju/oneroom/area/dto/AreaDto.java
  server/src/main/java/jeju/oneroom/area/entity/Area.java
  server/src/main/java/jeju/oneroom/area/mapper/AreaMapper.java
  server/src/main/java/jeju/oneroom/area/repository/AreaRepository.java
  server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
  server/src/main/java/jeju/oneroom/houseInfo/dto/HouseInfoDto.java
  server/src/main/java/jeju/oneroom/houseInfo/entity/HouseInfo.java
  server/src/main/java/jeju/oneroom/houseInfo/repository/HouseInfoRepository.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/dto/ReviewDto.java
  server/src/main/java/jeju/oneroom/review/mapper/ReviewMapper.java
  server/src/main/java/jeju/oneroom/si/controller/SiController.java
  server/src/main/java/jeju/oneroom/si/dto/SiDto.java
  server/src/main/java/jeju/oneroom/si/entity/Si.java
  server/src/main/java/jeju/oneroom/si/mapper/SiMapper.java
  server/src/main/java/jeju/oneroom/si/repository/SiRepository.java
  server/src/main/java/jeju/oneroom/town/controller/TownController.java
  server/src/main/java/jeju/oneroom/town/mapper/TownMapper.java
  server/src/main/java/jeju/oneroom/town/repository/TownRepository.java
  server/src/main/java/jeju/oneroom/user/entity/User.java
  server/src/main/java/jeju/oneroom/user/mapper/UserMapper.java
  server/src/test/java/jeju/oneroom/postComment/entity/PostCommentTest.java
Labels: refactor

#76 [BE] feat - #66 : Service 계층 1차 구현 및 ReviewController에 최신순 추천순 로직 구현
  server/src/main/java/jeju/oneroom/message/service/MessageService.java
  server/src/main/java/jeju/oneroom/review/controller/ReviewController.java
  server/src/main/java/jeju/oneroom/review/repository/ReviewRepository.java
  server/src/main/java/jeju/oneroom/review/service/ReviewService.java
  server/src/main/java/jeju/oneroom/user/service/UserService.java
Labels: bug, feat

#77 [BE] TestCode 복구
  server/src/test/java/jeju/oneroom/OneroomApplicationTests.java
  server/src/test/java/jeju/oneroom/Post/entitiy/PostTest.java
  server/src/test/java/jeju/oneroom/area/entity/AreaTest.java
  server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
  server/src/test/java/jeju/oneroom/postComment/entity/PostCommentTest.java
  server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
  server/src/test/java/jeju/oneroom/user/entity/UserTest.java
Labels: fix

#79 [BE] feat - #66 : Area, HouseInfo Service 1차 구현
  server/src/main/java/jeju/oneroom/area/controller/AreaController.java
  server/src/main/java/jeju/oneroom/area/dto/AreaDto.java
  server/src/main/java/jeju/oneroom/area/entity/Area.java
  server/src/main/java/jeju/oneroom/area/service/AreaService.java
  server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
  server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
  server/src/main/java/jeju/oneroom/review/mapper/ReviewMapper.java
  server/src/main/java/jeju/oneroom/user/mapper/UserMapper.java
  server/src/test/java/jeju/oneroom/area/entity/AreaTest.java
  server/src/test/java/jeju/oneroom/houseInfo/entity/HouseInfoTest.java
  server/src/test/java/jeju/oneroom/postComment/entity/PostCommentTest.java
  server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
  server/src/test/java/jeju/oneroom/user/entity/UserTest.java
Labels: feat, refactor

#80 [BE] feat - #67 : Area, HouseInfo Controller 2차 구현
  server/src/main/java/jeju/oneroom/area/controller/AreaController.java
  server/src/main/java/jeju/oneroom/area/entity/Area.java
  server/src/main/java/jeju/oneroom/area/service/AreaService.java
  server/src/main/java/jeju/oneroom/houseInfo/controller/HouseInfoController.java
  server/src/main/java/jeju/oneroom/houseInfo/service/HouseInfoService.java
  server/src/test/java/jeju/oneroom/area/entity/AreaTest.java
Labels: feat, refactor

#82 [BE] UserDto.Patch 수정 및 ReviewTest 수정
  server/src/main/java/jeju/oneroom/message/controller/MessageController.java
  server/src/main/java/jeju/oneroom/user/controller/UserController.java
  server/src/main/java/jeju/oneroom/user/dto/UserDto.java
  server/src/main/java/jeju/oneroom/user/entity/User.java
  server/src/main/java/jeju/oneroom/user/mapper/UserMapper.java
  server/src/main/java/jeju/oneroom/user/service/UserService.java
  server/src/test/java/jeju/oneroom/review/entity/ReviewTest.java
  server/src/test/java/jeju/oneroom/user/entity/UserTest.java
Labels: fix

#85 [FE] MainPage Markup 완료
  client/public/svg/whiteSearch.svg
  client/src/component/molecules/bestPosts/BestPosts.module.scss
  client/src/component/molecules/bestPosts/BestPosts.tsx
  client/src/component/molecules/loginMain/LoginMain.module.scss
  client/src/component/molecules/searchBar/SearchBar.module.scss
  client/src/component/molecules/searchBar/SearchBar.tsx
  client/src/component/organisms/modal/Modal.module.scss
  client/src/component/templates/header/Header.module.scss
  client/src/styles/Home.module.scss
Labels: feat
